### ISSUE TITLE
Can't install it on Windows 10

### ISSUE THREAD

**Issue by AmirhosseinSafari-Embedded** [hespanha/tenscalc#1]
Hi
First of all, I appreciate your attempt for creating this toolbox
I've tried to install this toolbox on Matlab but unfortunately I've got below error:
```matlab
Compiling...
writeGateway... done writeGateway (0.09 sec)   Compiling 10 gateways... Building with 'Microsoft Visual C++ 2012 (C)'.
Error using mex
initInstructionsTable.c
C:\Users\Myuser\Desktop\Folders\duties\Simulation\tenscalc-master\lib\csparse\initInstructionsTable.c(41) : fatal
error C1083: Cannot open include file: 'inttypes.h': No such file or directory



Error in gatewayCompile (line 112)
    eval(cmd);

Error in createGateway (line 680)
        gatewayCompile(compilerOptimization,folder,...

Error in compileInstructionsTable (line 39)
        createGateway('template','instructionsTableUTHash.c',...

Error in install_tenscalc (line 18)
compileInstructionsTable;
```
And my question is how can I solve this error, where should I get `inttypes.h` and also where should I put it?
Thanks

**Comment by hespanha** [comment]
Unfortunately, I don't have access to windows, but I'll see what I can do.
Which C compiler are you using? Also, what do you get when you do:

>> mex -setup C

at the matlab prompt.
Joao

**Comment by AmirhosseinSafari-Embedded** [comment]
Thanks Joao
This is output of the command you said:
```matlab
MEX configured to use 'Microsoft Visual C++ 2012 (C)' for C language compilation.
Warning: The MATLAB C and Fortran API has changed to support MATLAB
	 variables with more than 2^32-1 elements. You will be required
	 to update your code to utilize the new API.
```
If you need any information, let me know

**Comment by hespanha** [comment]
I fixed several issues with the windows installation. You should pull the latest version and try again, but likely I have not solved your problem because inttypes.h is a built-in header file that, as far as I can see, has only been included in MSVC since 2013 so MSVC 2012 does not have it. I suggest that you try with Microsoft Visual C++ 2015 or 2017, which are both free for individual developers. See notes at
	https://github.com/hespanha/cmextools <https://github.com/hespanha/cmextools>
Best,
Joao
